### ISSUE TITLE
Passive Mob Spawning seems low. 

### ISSUE THREAD

**Issue by ResqDiver1317** [ResqDiver1317/ThirdPeril_PerilousSkies#12]
Adjust mob spawning in Sponge and check clearlag

**Comment by ResqDiver1317** [comment]
Adjusted Sponge and CatClearLag configs to try and address this.

**Comment by MunchNStuff** [comment]
No mobs are spawning. Where is this config?

**Comment by ResqDiver1317** [comment]
As best as I can tell, neither of them really prevent spawning. CatClearLag simply looks if there is too many and will remove extras but it would post the message saying it did so. Sponge looks like it just affects activation range, not actual spawn amounts. I've upped the range but that doesn't appear to be doing anything. The only other thing I can think of, and this goes with what little useful stuff there is online, is that maybe another mod in the pack is affecting spawning but I have absolutely no idea what other mod would be doing that.

**Comment by MunchNStuff** [comment]
if you UP the range doesn't that mean we have to farther away for them to spawn? maybe lower it?

**Comment by ResqDiver1317** [comment]
No, the activation range is the maximum distance it will try to spawn at. Lower number means it has to be closer to spawn but too low and it conflicts with the normal 16 block minimum distance.

**Comment by MunchNStuff** [comment]
Maybe reset it back to default and we go from there.

**Comment by ResqDiver1317** [comment]
Fixed
