### ISSUE TITLE
Add Aluminum and Tin to diamond level  mesh for compressed sand too

### ISSUE THREAD

**Issue by b12arr0** [ResqDiver1317/ThirdPeril_PerilousSkies#15]
I forgot to ask that be added for compressed sand too.

My compressed sand auto-sieve is making a lot of silver right now. :)

**Comment by MunchNStuff** [comment]
Added to config, merge pending.

**Comment by ResqDiver1317** [comment]
commit https://github.com/ResqDiver1317/ThirdPeril_PerilousSkies/commit/ce6b124ad855b2c0a98545dca4615548855b43ff from Munch's PR

**Comment by ResqDiver1317** [comment]
Update Log - https://github.com/ResqDiver1317/ThirdPeril_PerilousSkies/commit/cc6d6f395b6fe14b9d3cc9d5413c489a3a57b0ed
