### ISSUE TITLE
Liquid Slime (Tinkers Construct mod) 

### ISSUE THREAD

**Issue by DarkRaging** [ResqDiver1317/ThirdPeril_PerilousSkies#16]
**Is your feature request related to a problem? Please describe.**
recipe not working
**Describe the solution you'd like**
A clear and concise description of what you want to happen. If suggesting a new recipe to be added, or an existing recipe to be changed, please include a sample of what you feel the recipe should be. For crafting recipes, list the items to be used for crafting (including the mod the item is from). For recipes that require a pattern, please do so in the following format:
item1 item2 item3 in a Cauldron fill with milk 
item4 item5 item6 drop a slimeball (blue, purple) to
item7 item8 item9 craft liquid blue, purple slime

**If you are suggesting a mod to be added to the Perilous Skies pack, please include the link.**
Post the link to the mods CurseForge page.

**Additional context**

**Comment by MunchNStuff** [comment]
I think this crafting of liquid slime would be easier done with the Tinkers smeltery. Since there is already a way to melt the purple slime in the smeltery would it bo ok to add a recipe to melt the blue slime balls?

**Comment by ResqDiver1317** [comment]
This would require adding 5 recipes to Tinkers vs 3 to the cauldron

**Comment by ResqDiver1317** [comment]
HOPEFULLY https://github.com/ResqDiver1317/ThirdPeril_PerilousSkies/commit/7b502060797e4d852d01a6a6da0c12739324de2e

**Comment by ResqDiver1317** [comment]
If this doesn't work, gonna just make this a basic crafting recipe to get the slime buckets

**Comment by MunchNStuff** [comment]
Did you test this in you test pack yet?

**Comment by ResqDiver1317** [comment]
I did. I had to make a change to the recipes when testing that I haven't put in here yet but will momentarily. Accidentally set it to require heat which wouldn't be good with wood cauldrons

**Comment by ResqDiver1317** [comment]
https://github.com/ResqDiver1317/ThirdPeril_PerilousSkies/commit/ea6b860a875b9de9e207b7cfc447fcbf3683990a

**Comment by ResqDiver1317** [comment]
Update Log - https://github.com/ResqDiver1317/ThirdPeril_PerilousSkies/commit/cc6d6f395b6fe14b9d3cc9d5413c489a3a57b0ed
