### ISSUE TITLE
Electrolytic Seperator

### ISSUE THREAD

**Issue by DarkRaging** [ResqDiver1317/ThirdPeril_PerilousSkies#18]
**Describe the bug**
A clear and concise description of what the bug is. Be sure to state what mod(s) this issue is related to.
 There is no configuration option for the electrolytic separator, as well as the rotary condensentrator
**To Reproduce**
1. Go to '...' machine
2. Click on '....' open up
3. Scroll down to '....' on right there no configuration tab

**Expected behavior**
 should be able setup input /output by colors to items, fluids, and gases
**Screenshots**

**Crash Reports**
If this is related to a crash, please upload your crash report (upload the actual crash report file, please do not copy/paste your crash report into this issue).

**Additional context**

**Comment by ResqDiver1317** [comment]
https://ftb.fandom.com/wiki/Electrolytic_Separator
