### ISSUE TITLE
Ender Dragon death should produce 1 dragon egg

### ISSUE THREAD

**Issue by b12arr0** [ResqDiver1317/ThirdPeril_PerilousSkies#20]
Not sure if this is a bug or just a request.  :)  

Although it is craftable by way of dragon egg chunks via Mystical Agriculture or the Loot Fabricator via Deep Mob Learning, the death of a respawned Ender Dragon in the End should produce 1 dragon egg each time.

**Comment by b12arr0** [comment]
I killed about 10 dragons with no resulting dragon egg.  I did get dragon scales a few times though.

**Comment by ResqDiver1317** [comment]
Gonna add this in the next update to address this.
https://www.curseforge.com/minecraft/mc-mods/equaldragons

**Comment by ResqDiver1317** [comment]
Update Log - https://github.com/ResqDiver1317/ThirdPeril_PerilousSkies/commit/cc6d6f395b6fe14b9d3cc9d5413c489a3a57b0ed
