### ISSUE TITLE
blizz and probly blitz and basalz, they dont seem to spawn anywhere @thermal

### ISSUE THREAD

**Issue by sparitsa** [ResqDiver1317/ThirdPeril_PerilousSkies#22]
**Describe the bug**
A clear and concise description of what the bug is. Be sure to state what mod(s) this issue is related to.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Crash Reports**
If this is related to a crash, please upload your crash report (upload the actual crash report file, please do not copy/paste your crash report into this issue).

**Additional context**

**Comment by MunchNStuff** [comment]
If we add the XL FOOD MOD seeds to sifting, there is a way to make the mob seeds with animal crops.

**Comment by ResqDiver1317** [comment]
They do spawn. I've had the blitz spawn in my smelter. The problem is they need specific biomes and terrain to spawn which is hard to do in skyblock. May look into making their drops part of gravel, sand, and dust sieving as well. (Spread them out, not all one base material)

**Comment by MunchNStuff** [comment]
yeah we can basalz to gravel and bliz to dust maybe?

**Comment by ResqDiver1317** [comment]
Sieve Recipes - https://github.com/ResqDiver1317/ThirdPeril_PerilousSkies/commit/a572f01c3803e41a3665edf281cf79e0afe29223

Crafting dust to rods - https://github.com/ResqDiver1317/ThirdPeril_PerilousSkies/commit/c3279d0111c08181c7150ea8973f86a410b55e9a

**Comment by ResqDiver1317** [comment]
stupid typos... https://github.com/ResqDiver1317/ThirdPeril_PerilousSkies/commit/a1859c09b626c45f8af962695358e3e1a0a1700d

**Comment by ResqDiver1317** [comment]
Update Log - https://github.com/ResqDiver1317/ThirdPeril_PerilousSkies/commit/cc6d6f395b6fe14b9d3cc9d5413c489a3a57b0ed
