### ISSUE TITLE
Remove Decocraft stuff from JEI

### ISSUE THREAD

**Issue by b12arr0** [ResqDiver1317/ThirdPeril_PerilousSkies#4]
I think you have Decocraft in the pack to allow stuff in the spawn airplane but nothing is craftable from it in game.   If possible, could Decocraft items be removed from JEI results?

**Comment by ResqDiver1317** [comment]
Individual items for Decocraft are typically not craftable directly. You need to craft the Decobench from Decocraft, load it with the colored clays, and then you create the items in the bench.
I did just test and confirm the bench is craftable.

**Comment by b12arr0** [comment]
Thanks! This has been verified!
