### ISSUE TITLE
Consider removing Primitive Crafting mod

### ISSUE THREAD

**Issue by b12arr0** [ResqDiver1317/ThirdPeril_PerilousSkies#5]
I'm tired of crafting sticks and cobble paths when I just want to simply move all my oak wood and or cobble stone from my inventory to the chest/storage that I have open.   I'm just so used to the vanilla way of doing inventory clearing that I'm several stacks of sticks or cobble paths into it by the time I remember/realize what is going on. 

Just a suggestion...        :)

**Comment by ResqDiver1317** [comment]
I think the idea was for progression where the normal 2x2 craft window in your inventory isn't there until you hit a certain progression but we are not using progressions like that so I would agree that this mod is not needed so I will see about removing it for the next update.

**Comment by ResqDiver1317** [comment]
Removed in 1.10 update.
