### ISSUE TITLE
Add Carry On Mod to the modpack

### ISSUE THREAD

**Issue by b12arr0** [ResqDiver1317/ThirdPeril_PerilousSkies#6]
Jugs and I would like to be able to pick up animals. 

**Describe the solution you'd like**
Would like to move my  chickens and not have to rely on seeds to get them moved.  

**If you are suggesting a mod to be added to the Perilous Skies pack, please include the link.**
https://www.curseforge.com/minecraft/mc-mods/carry-on

**Comment by MunchNStuff** [comment]
This is not needed. We already have a mod for this. Extra Utilities 2 Golden Lasso does exactly this! WOOOOO, nice suggestion though! Keep em' comin!

**Comment by ResqDiver1317** [comment]
https://github.com/ResqDiver1317/ThirdPeril_PerilousSkies/commit/dc47a05791d73c8e5c9b32e421bd1a7d6e102140
