### ISSUE TITLE
Extra Utils Flat Transfer Nodes do not work

### ISSUE THREAD

**Issue by ResqDiver1317** [ResqDiver1317/ThirdPeril_PerilousSkies#7]
**Describe the bug**
EU Flat Transfer nodes do not appear to actually transfer items

**To Reproduce**
Place 2 chests.
Place items in 1 chest
Place Flat Transfer Node between chests.

**Expected behavior**
Items should transfer from one chest to the other via the FTN.

**Comment by MunchNStuff** [comment]
Confirmed these are not working as intended.
